version: '3.3'

services:
  mongodb:
    image: remote-docker.artifactory.swisscom.com/mongo:7.0
    container_name: teams-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: teams
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - teams-network

volumes:
  mongodb_data:
    driver: local

networks:
  teams-network:
    driver: bridge